### ISSUE TITLE
Additional option calUsePickersAndPrevNextMonth is needed.

### ISSUE THREAD

**Issue by slavap** [jtsage/jquery-mobile-datebox#346]
It could be useful to have an ability to hide header with calNoHeader="true", but still have Prev and Next month buttons available on the pickers band. See attachment.
![usepickers](https://cloud.githubusercontent.com/assets/4129763/4929435/34654bae-6553-11e4-9bff-e928d4bfdc4e.png)

UPDATE >> Workaround: 
Define it as calNoHeader="false" usePickers="true"
Then it's possible to achieve needed functionality with the following CSS:

``` css
.ui-datebox-container .ui-datebox-gridheader .ui-datebox-gridlabel {
  display: none;
}
.ui-datebox-container .ui-datebox-gridheader + .ui-datebox-grid {
  clear: none;
  padding: 0 5px 0 5px !important;
}
```

Not sure if it's good solution, IMO additional option is a better way.
![usepickersandprevnextmonth](https://cloud.githubusercontent.com/assets/4129763/4930054/abdfc150-655d-11e4-8fe5-0e7932c53d1a.png)
