### ISSUE TITLE
calUsePickersIcons minor issues.

### ISSUE THREAD

**Issue by slavap** [jtsage/jquery-mobile-datebox#347]
It's related to https://github.com/jtsage/jquery-mobile-datebox/issues/346
Just not sure it's a good idea to comment on a closed issue.

calNoHeader="true", calUsePickers="true", and calUsePickersIcons="true".
It's not quite working for me. I'm getting the following:
![usepickersicons](https://cloud.githubusercontent.com/assets/4129763/4945268/ec4ea014-6605-11e4-8595-2d4cff9564c3.png)

BUT expecting:
![usepickersicons_expected](https://cloud.githubusercontent.com/assets/4129763/4945271/fb00a710-6605-11e4-8b6d-a333af163cc7.png)

It could be fixed by adding: 

``` css
display: inline-block; width: 540px; /* 230px for standard calbox */
```

to control group's parent div, but the problem is that exact width must be specified depending on the current width of calbox :-( I don't know a good way how to make div cover all available space between float left and right elements.

Also ui-controlgroup padding should be fixed to: 

``` css
padding: 0 10px 5px 10px !important;
```

At the moment I've ended up with the following CSS:

``` css
.ui-datebox-container .ui-datebox-gridheader + div {
    /* display: inline-block; - not needed anymore, fixed */
    width: 540px;
}
/* not needed anymore, fixed
.ui-datebox-container .ui-datebox-gridheader + div > .ui-controlgroup {
    padding: 0 10px 5px 10px !important;
}*/

.ui-datebox-container { 
    width: 600px !important;
}
.ui-datebox-container .ui-datebox-griddate.ui-btn { 
    width: 82px;
    height: 57px;
    line-height: 19px;
}
.ui-datebox-container .ui-datebox-griddate.ui-datebox-griddate-label {
    width: 82px;
}
```

Which gives me the following look and feel:
![calboxformatted](https://cloud.githubusercontent.com/assets/4129763/4947166/67d86efe-661f-11e4-85f9-25c40e6fae46.png)
