### ISSUE TITLE
Inline datebox's z-index must be auto to prevent various glitches in mobile browsers.

### ISSUE THREAD

**Issue by slavap** [jtsage/jquery-mobile-datebox#357]
It's especially bad in Android Chrome.
Possible fix is the following:

``` css
.ui-datebox-container.ui-datebox-inline {
  z-index: auto !important;
}
```
